//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DocGia
    {
        public tbl_DocGia()
        {
            this.tbl_PhieuMuonTra = new HashSet<tbl_PhieuMuonTra>();
        }
    
        public string MaDG { get; set; }
        public string TenDG { get; set; }
        public string MaSV { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string Lop { get; set; }
    
        public virtual ICollection<tbl_PhieuMuonTra> tbl_PhieuMuonTra { get; set; }
    }
}
