//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PhieuMuonTra
    {
        public tbl_PhieuMuonTra()
        {
            this.tbl_ChiTietPhieuMuon = new HashSet<tbl_ChiTietPhieuMuon>();
        }
    
        public string MaPM { get; set; }
        public string MaDG { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayHenTra { get; set; }
    
        public virtual ICollection<tbl_ChiTietPhieuMuon> tbl_ChiTietPhieuMuon { get; set; }
        public virtual tbl_DocGia tbl_DocGia { get; set; }
        public virtual tbl_NhanVien tbl_NhanVien { get; set; }
    }
}
