//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sach
    {
        public tbl_Sach()
        {
            this.tbl_ChiTietPhieuMuon = new HashSet<tbl_ChiTietPhieuMuon>();
            this.tbl_TacGia = new HashSet<tbl_TacGia>();
        }
    
        public string MaSach { get; set; }
        public int MaLoaiSach { get; set; }
        public string MaViTri { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> NamXB { get; set; }
        public Nullable<int> MaNXB { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> SL { get; set; }
    
        public virtual ICollection<tbl_ChiTietPhieuMuon> tbl_ChiTietPhieuMuon { get; set; }
        public virtual tbl_LoaiSach tbl_LoaiSach { get; set; }
        public virtual tbl_NhaXB tbl_NhaXB { get; set; }
        public virtual tbl_ViTri tbl_ViTri { get; set; }
        public virtual ICollection<tbl_TacGia> tbl_TacGia { get; set; }
    }
}
