//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TaiKhoan
    {
        public string Name { get; set; }
        public string Pass { get; set; }
        public string MaNV { get; set; }
    
        public virtual tbl_NhanVien tbl_NhanVien { get; set; }
    }
}
