//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NgSD
    {
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string  MaNV { get; set; }
        public string QuyenTruyCap { get; set; }
        public Nullable<System.DateTime> NgayDangKi { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
    }
}
