//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanCaPhe.Module
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CoffeManagerProjectEntities : DbContext
    {
        public CoffeManagerProjectEntities()
            : base("name=CoffeManagerProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tbl_ChitietHD> tbl_ChitietHD { get; set; }
        public DbSet<tbl_HoaDon> tbl_HoaDon { get; set; }
        public DbSet<tbl_NgSD> tbl_NgSD { get; set; }
        public DbSet<tbl_NhanVien> tbl_NhanVien { get; set; }
        public DbSet<tbl_ThucDon> tbl_ThucDon { get; set; }
        public DbSet<View_BaoCaoHoaDon> View_BaoCaoHoaDon { get; set; }
        public DbSet<View_CTHD_HD> View_CTHD_HD { get; set; }
        public DbSet<View_ChiTietHD> View_ChiTietHD { get; set; }
        public DbSet<View_HD_NV> View_HD_NV { get; set; }
        public DbSet<View_HoaDon> View_HoaDon { get; set; }
        public DbSet<View_NgSD> View_NgSD { get; set; }
        public DbSet<View_NhanVien> View_NhanVien { get; set; }
        public DbSet<View_ThucDon> View_ThucDon { get; set; }
    
        public virtual ObjectResult<BAOCAOTHEONGAY_Result> BAOCAOTHEONGAY(Nullable<int> thang, Nullable<int> nam, Nullable<int> ngay)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BAOCAOTHEONGAY_Result>("BAOCAOTHEONGAY", thangParameter, namParameter, ngayParameter);
        }
    
        public virtual ObjectResult<BAOCAOTHEOTHANG_Result> BAOCAOTHEOTHANG(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BAOCAOTHEOTHANG_Result>("BAOCAOTHEOTHANG", thangParameter, namParameter);
        }
    
        public virtual int CapNhatCTHD(string maHD, string maSP, Nullable<int> soluong, Nullable<int> donGia, Nullable<double> kM)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("Soluong", soluong) :
                new ObjectParameter("Soluong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            var kMParameter = kM.HasValue ?
                new ObjectParameter("KM", kM) :
                new ObjectParameter("KM", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatCTHD", maHDParameter, maSPParameter, soluongParameter, donGiaParameter, kMParameter);
        }
    
        public virtual int CapNhatHoaDon(string maHD, string maNV, Nullable<System.DateTime> ngayCapNhat, Nullable<int> soCa)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var ngayCapNhatParameter = ngayCapNhat.HasValue ?
                new ObjectParameter("NgayCapNhat", ngayCapNhat) :
                new ObjectParameter("NgayCapNhat", typeof(System.DateTime));
    
            var soCaParameter = soCa.HasValue ?
                new ObjectParameter("SoCa", soCa) :
                new ObjectParameter("SoCa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatHoaDon", maHDParameter, maNVParameter, ngayCapNhatParameter, soCaParameter);
        }
    
        public virtual int CapNhatThucDon(string iD, string ten, Nullable<int> donGia, string dVT)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatThucDon", iDParameter, tenParameter, donGiaParameter, dVTParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> countUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("countUser");
        }
    
        public virtual int EDITCTHD(string maHD, string maSP, Nullable<int> soluong, Nullable<int> donGia, Nullable<double> kM)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("Soluong", soluong) :
                new ObjectParameter("Soluong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            var kMParameter = kM.HasValue ?
                new ObjectParameter("KM", kM) :
                new ObjectParameter("KM", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EDITCTHD", maHDParameter, maSPParameter, soluongParameter, donGiaParameter, kMParameter);
        }
    
        public virtual ObjectResult<LayDLBCHD_Result> LayDLBCHD(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDLBCHD_Result>("LayDLBCHD", thangParameter, namParameter);
        }
    
        public virtual ObjectResult<LayDLHD_Result> LayDLHD(string maHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDLHD_Result>("LayDLHD", maHDParameter);
        }
    
        public virtual int proCapNhatNV(string maNV, string tenNV, string gioiTinh, Nullable<System.DateTime> ngaySinh, string diaChi, string sDT)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proCapNhatNV", maNVParameter, tenNVParameter, gioiTinhParameter, ngaySinhParameter, diaChiParameter, sDTParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<string> sp_nhanvien_id()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_nhanvien_id");
        }
    
        public virtual ObjectResult<string> sp_hoadon_id()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_hoadon_id");
        }
    }
}
