//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanCaPhe.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ThucDon
    {
        public tbl_ThucDon()
        {
            this.tbl_ChitietHD = new HashSet<tbl_ChitietHD>();
        }
    
        public string ID { get; set; }
        public string Ten { get; set; }
        public string DVT { get; set; }
        public Nullable<int> DonGia { get; set; }
    
        public virtual ICollection<tbl_ChitietHD> tbl_ChitietHD { get; set; }
    }
}
