//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanCaPhe.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_NhanVien
    {
        public string Mã_Nhân_Viên { get; set; }
        public string Tên_Nhân_Viên { get; set; }
        public string Giới_Tính { get; set; }
        public Nullable<System.DateTime> Ngày_Sinh { get; set; }
        public string Địa_Chỉ { get; set; }
        public string Số_Điện_Thoại { get; set; }
    }
}
