//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanCaPhe.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_HD_NV
    {
        public string Mã_Hóa_Đơn { get; set; }
        public string Mã_Nhân_Viên { get; set; }
        public string Tên_Nhân_Viên { get; set; }
        public Nullable<System.DateTime> Ngày_Cập_Nhật { get; set; }
        public Nullable<int> Ca_Số { get; set; }
    }
}
