//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanCaPhe.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ThucDon
    {
        public int Mã_Đồ_Uống { get; set; }
        public string Tên { get; set; }
        public string Đơn_Vị_Tính { get; set; }
        public Nullable<int> Đơn_Giá { get; set; }
    }
}
