//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanCaPhe.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CTHD_HD
    {
        public string ID { get; set; }
        public string Tên_Món { get; set; }
        public Nullable<int> Số_Lượng { get; set; }
        public Nullable<int> Đơn_Giá { get; set; }
        public Nullable<double> Giảm_Giá { get; set; }
        public Nullable<int> Thành_Tiền { get; set; }
    }
}
