//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanCaPhe.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_NgSD
    {
        public string Tài_Khoản { get; set; }
        public string Mật_Khẩu { get; set; }
        public string Mã_Nhân_Viên { get; set; }
        public string Quyền_Truy_Cập { get; set; }
        public Nullable<System.DateTime> Ngày_Đăng_Kí { get; set; }
        public Nullable<System.DateTime> Ngày_Hết_Hạn { get; set; }
    }
}
