//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanCaPhe.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BaoCaoHoaDon
    {
        public string MaHD { get; set; }
        public string Ten { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> ThanhTien { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<double> KhuyenMai { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string TenNV { get; set; }
        public Nullable<int> CaSo { get; set; }
    }
}
