//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeWFP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChiTietPhieuMuon
    {
        public string MaPM { get; set; }
        public string MaSach { get; set; }
        public Nullable<int> SL { get; set; }
    
        public virtual tbl_PhieuMuonTra tbl_PhieuMuonTra { get; set; }
        public virtual tbl_Sach tbl_Sach { get; set; }
    }
}
